apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - secrets/sealed-oauth.yaml
  - secrets/sealed-email.yaml

helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.1.3
    releaseName: oauth2-proxy
    valuesFile: values.yaml
    includeCRDs: true