---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-emails
  namespace: kube-system
spec:
  encryptedData:
    restricted_user_access: AgBR3eC34y6Y2cRAfIc60Hv86iDQHWoTuqB/60syE71g2uiVXHgmuQHSrngV/pOU+N4eobuVHF7UbMHD6jQrsu8eUizfyaTOEf58lU8ThEEXvJ1XOzJf6CrpH90ENsWMThB4cMBCx8fh67LOzx9AwjmvxuNO67pq6C5BMlDP27lRn47tYkbGV6XF1trAp3gy9/Uesfnd6XiyI+y9KqeugK6BueOoWDDcYVeDhyM08ZSF30L1RNKv/cDJyWh45lEDktePrU3IXhHpTwncfvsy/BDPM0WVtTFzy/JDvlhVS0TK0RjpBlJy4uBvqThV6k/JqLDGJ5wzaM0CY/U1F7V/MRlpAdte0ZLMx2sfDZ25iE382HrG8rHYdnNK+HD/HP8gIkywrUREog4PvsylOmfif1oBwzAMWK3AsGnQqPpARNpxAiMf5IJvXH7wjQ8aazHehTLTUh5dVmi+vib/3c2OOjJ+yW7+hTSb4ufqsj3dzMWoexNzt8Y/H+3PtKWGVG3zeMXKA9BFKXyn1pFSudCll9HYjseL0ch2zl5LVmIpq9be3xV8LriuNVYeQ0alM4uMmE7tmu+XXgeX1NsCcIX2UrU7vcrvN+sYaQximS0n18TzI9LL5X2e5oi46cEfXf1gYLU+K+tfOCcQg2kbGhqcGhiQ+8SlLUj+xx8HyX8YgI26NFdSC5KhUarKxj/uw5dVNPv+XRpWcDiXjS6twywR40SinHa4IkE=
  template:
    metadata:
      name: oauth2-proxy-emails
      namespace: kube-system
    type: Opaque
