apiVersion: v1
kind: Pod
metadata:
  name: ecr-fail-test
spec:
  containers:
    - name: test-container
      image: 123644281329.dkr.ecr.ap-northeast-2.amazonaws.com/backend:latest
      command: ["/bin/sh", "-c", "sleep 3600"]

  imagePullSecrets:
    - name: ecr-secret

  nodeSelector:
    role: worker