apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-sse-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"  
spec:
  tls:
    - hosts:
        - www.glok.store      
      secretName: glok-tls-secret
  rules:
    - host: www.glok.store
      http:
        paths:
          - path: /sse
            pathType: Prefix
            backend:
              service:
                name: mcp-service
                port:
                  number: 80
          - path: /messages
            pathType: Prefix
            backend:
              service:
                name: mcp-service
                port:
                  number: 80