apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glok-wildcard-cert
  namespace: kube-system
spec:
  secretName: glok-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.glok.store"
  - "glok.store"