{
 "title": "안준섭의 대시보드",
 "tags": [
  "main",
  "안준섭"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "서비스", "query": { "query": "label_values(job)" } },
   { "name": "trace_id" }
  ]
 },
 "panels": [
  {
   "title": "${service_name} RED Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_request_duration_seconds_count{job=\"$service_name\"}[5m]))",
     "legendFormat": "요청량 (RPS)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_server_request_duration_seconds_bucket{job=\"$service_name\"}[5m])))",
     "legendFormat": "응답속도 (P95)"
    },
    {
     "expr": "sum by (job) (rate(http_server_request_duration_seconds_count{job=\"$service_name\", http_response_status_code=~\"5.*\"}[5m]))",
     "legendFormat": "에러율 (Errors)"
    }
   ]
  },
  {
   "title": "${service_name} Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{exporter=\"OTLP\", job=\"$service_name\"} | json | line_format \"{{.body}}\""
    }
   ]
  },
  {
   "title": "${service_name} Trace",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "filters": [
      {
       "id": "5dd662f5",
       "isCustomValue": true,
       "operator": "!=",
       "scope": "span",
       "tag": "db.statement",
       "value": [
        "\" \""
       ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name = \"$service_name\" && span.db.statement != \"\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "${service_name} Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.db.statement!=\"\" && resource.service.name=\"$service_name\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "traces",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 31 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "${trace_id}", "tableType": "traces" }
   ]
  },
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 21, "w": 10, "x": 14, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$service_name\"} |= \"${trace_id}\""
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"$service_name\", jvm_memory_type=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(area) (jvm_memory_used_bytes{job=\"$service_name\", jvm_memory_type=\"non_heap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}