apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis

      nodePort: 30001

    - port: 9121
      targetPort: 9121
      name: metrics