apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-tempo
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  tempo.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 27,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "tempo",
            "uid": "tempo-v2"
          },
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "edges": {},
            "layoutAlgorithm": "layered",
            "nodes": {},
            "zoomMode": "cooperative"
          },
          "pluginVersion": "12.3.0",
          "targets": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "tempo-v2"
              },
              "filters": [
                {
                  "id": "f97b2dae",
                  "operator": "=",
                  "scope": "span"
                }
              ],
              "limit": 20,
              "metricsQueryType": "range",
              "queryType": "serviceMap",
              "refId": "A",
              "serviceMapUseNativeHistograms": false,
              "tableType": "traces"
            }
          ],
          "title": "Service Topology",
          "type": "nodeGraph"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "showValues": false,
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": 0
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "12.3.0",
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(traces_spanmetrics_calls_total[1m])) by (service)",
              "legendFormat": "__auto",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "RED Metrics",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "tempo",
            "uid": "tempo-v2"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "cellOptions": {
                  "type": "color-text"
                },
                "footer": {
                  "reducers": []
                },
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": 0
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Trace ID"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 315
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Service"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 276
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Start time"
                },
                "properties": [
                  {
                    "id": "custom.width",
                    "value": 286
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 10
          },
          "id": 3,
          "options": {
            "cellHeight": "sm",
            "showHeader": true
          },
          "pluginVersion": "12.3.0",
          "targets": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "tempo-v2"
              },
              "filters": [
                {
                  "id": "49a0c625",
                  "isCustomValue": true,
                  "operator": "!=",
                  "scope": "span",
                  "tag": "db.statement",
                  "value": [
                    "\" \""
                  ]
                },
                {
                  "id": "service-name",
                  "isCustomValue": false,
                  "operator": "=",
                  "scope": "resource",
                  "tag": "service.name",
                  "value": [
                    "backend-service"
                  ],
                  "valueType": "string"
                }
              ],
              "limit": 20,
              "metricsQueryType": "range",
              "query": "{span.db.statement!=\" \" && resource.service.name=\"backend-service\"}",
              "queryType": "traceql",
              "refId": "A",
              "serviceMapUseNativeHistograms": false,
              "tableType": "traces"
            }
          ],
          "title": "API 응답시간",
          "transparent": true,
          "type": "table"
        }
      ],
      "preload": false,
      "schemaVersion": 42,
      "tags": [
        "main"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-24h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Tempo, Prometheus",
      "uid": "adt9n7m",
      "version": 3
    }