---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    api-url: AgBBVcRDLaJcsopS+zE2/xG2eLmCJ23PIokDNNJ/TMuVXhB0RPO7Lsap1hQAlJr3znmiek9CL8mpNBtu9In5TpfoLjPEZqjZSVoTN3I+FtGoBa4rph2bV2gScqRrds2T81jCJvBL4UTeQl6Ope4wgl6NW4+Dy9bQD60YAB95v/Li295D0szg8Cf1lunMMaRV4uK0pGRu/t5RIjMELjcxnrulZ17rCsIXfAPRrxaK/1fUs3CRmZHsIWYOxm0hm2yRoU/7uvQ4FxfoHCeX5C9bf/FPS7yZf/ZdsPEnkaHooG3CNdU7tD2jnVeDQs8tZ2p7uD5/xf05EsybsbgppeAkz9ppXizGFRmLGT1eZxQUPXcTks60fiWQkcg5UhGgLRhxFp/T2qKCRxTzCFIfsP/498iDGvSP3+4m2V8vSGuvn1TUnXqghgJzgWE1haj6g+3eQsTjI5WbCAtXKUKXCZz6AVfP/+v6WMLFSXUPBPnyJqK+P5Tc1SdY4AdaDRxDxr8YLFlD7Cx9u3NB+9yxgYlKjYbXA1DcebX7qJFUfll0mN/JYSJ8GkLsHhCmu7YDk7dlk0lDZHhdDROOrZWeXXMTN0M+jWgbJF/rVZYU3SNOXFXZ9KDJPFNQbIdbeJymTydRqUDQ6iqfFx0n8vRE0q1p6SDN5ZN5CRBM0eIxPr5j/sfjHXvJAbXJspbZZyvkfFfwdvUVBpnOw6OgeyZxFnTjFPQbCj85KfJ7JVvTZrqfizmkcATLZG+q05hUnT1PGDifD1XyI2R/YXtjHJXBrBuN90lXBHBE1BFniRvljai5di60wZY=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
