apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: rancher/library-busybox:1.28.0
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "mkdir -p /data && chmod 777 /data"]
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists