apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: 123644281329.dkr.ecr.ap-northeast-2.amazonaws.com/mcp-server
          ports:
            - name: http
              containerPort: 8080
          # resources:
          #   requests:
          #     cpu: 1m
          #     memory: 4Mi
          #   limits:
          #     cpu: 10m
          #     memory: 12Mi
      imagePullSecrets:
        - name: ecr-secret