---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nth-slack-secret
  namespace: kube-system
spec:
  encryptedData:
    webhookurl: AgASrn4gm7SZ6DtoNtkD5+R0P3kP+tcSPj0+bnmSULJ5wYigYAZgFDvtSQJrH/+nNDUFxT+bAA38NzqkH9qdZt46uCnbWFBcies6V0CPwNWQdV4Z3UdrkmFMnTCFQJtnW/nwsI1eWR9kiB7bC0q0tzyKEeUuOPg4LYh+RweBdcxjDLFLgRWyCxlvT5vi9WvHPO203OTvTa4C3ggDzKXQi6vaIN+0eLfDQoQ2noiKqgL2szt3EJaM5/6o85k7N668o0YDr/42VQqqdb2rZ26U7gDgbXxTF5hCN6RoreneiKkGigapjs215dh3U2khFCTpNijEj4Azlr7mFIrdyg9/sd0D/3lVqljYTTEGTWlMlDgZo++qBSteZh7r2s0oC1tNZ0/clWzYWv6XPBe4/XpNRg8aZHGoUCj84vruoM7yuKkTD+4SBzzChgiaUBQ1xwlPQ0bAc73vtnjtu2WmY5V6nXNTrDXkIKfu56fQBM/sQuRgDPGkjwkKjTW6Wk7Sl+iuIsbfmRmPjLtMWYmQay2ANTfHJNhXBev+Ow0HMxe9CtJhNQQAE44aLOFB23otJhlievEx78Rhf60ya7YuWd1Cq9ob+9qUPMfiNFcAG8IR0ZxMJLsUErZ95cBB2gibcYciEheFTS401h/BTWM7BnYsaRpSxfXxnFaX3h4yCQtO3FerxxeywPNFAf0HD6hgUqEG+xOue0WnogpigmcwQEWzfA+iFYX/aAYeLU/kqZ1fRX8CJbgbk6rfc9xJsYrtv3lDSTZDMW7b1PuAPhthhOpm4wscQ8WSSuZdm44T6xJXohujXaw=
  template:
    metadata:
      name: nth-slack-secret
      namespace: kube-system
    type: Opaque
