apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aws-node-termination-handler
  namespace: kube-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
  selector:
      matchLabels:
        app.kubernetes.io/name: aws-node-termination-handler